version: '3.8'

services:
  hospital-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/hospital_management
      - SESSION_SECRET=hospital-secret-2024
      - JWT_SECRET=jwt-secret-2024
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - PORT=5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
